---
- hosts: mywebservers
  become: yes
  tasks:
  - name: install java on ubuntu node
    apt:
      name: 
      state: present
    when: ansoble_os_family =="Debian"

  - name: install java on redhat node
    ansible.builtin.dnf:
       name: 
       state: present
    when: ansible_os_family =="RedHat"