---
- hosts: 172.31.5.207
  become: yes
  tasks:
  - name: install git
    apt:
      name: git
      state: present
    tags: mygit
    
  - name: install tree
    apt:
       name: tree
       state: present
    tags: mytree